language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r tests/requirements.txt"
# command to run tests
script: py.test -vv
# run in a docker container
sudo: false
notifications:
  email: false
